# Build stage
FROM debian:trixie-slim AS builder

RUN apt-get update && apt-get install -y \
    build-essential \
    libsqlite3-dev \
    zlib1g-dev \
    git

WORKDIR /app

RUN git clone https://github.com/mapbox/tippecanoe.git
WORKDIR /app/tippecanoe
RUN make -j

# Executable stage
FROM debian:trixie-slim

WORKDIR /tippecanoe

COPY --from=builder /app/tippecanoe/tippecanoe* /tippecanoe

COPY gen_tiles.sh /tippecanoe/gen_tiles.sh
RUN chmod a+x /tippecanoe/gen_tiles.sh

ENV PATH="/tippecanoe:$PATH"