# From Google
google_analytics_id: "<GA_ID>"
# From https://cloud.maptiler.com/account/keys/
maptiler_api_key: "<API_KEY>"

# Location where deployment will be stored
deploy_dir: "{{ build_dir }}/landvalue"

# tile.json parameters
hostname: "localhost:8080"
scheme: "http"
version: 1

# Gzip tiles for local nginx serving with gzip_static
gzip_tiles: true
