input_dir: "{{ working_dir }}/inputs"
statewide_gdb: "{{ input_dir }}/ct.gdb"
cama_dir: "{{ input_dir }}/Parcel Collection 2024/CAMA_By_COG"

build_dir: "{{ working_dir }}/tmp"
geojson_dir: "{{ build_dir }}/geojson"
tiles_dir: "{{ build_dir }}/tiles"
