---
- name: Process Land Value and Generate Map Tiles
  hosts: localhost

  tasks:
    - name: Install Python dependencies
      ansible.builtin.pip:
        requirements: "{{ build_dir }}/ansible/requirements.txt"

    - name: Generate GeoJSON
      ansible.builtin.command:
        cmd: "python3 '{{ build_dir }}/src/main.py'"
        chdir: "{{ build_dir }}"
    
    - name: Generate Map Tiles
      community.docker.docker_compose_v2_run:
        project_src: "{{ build_dir }}/tippecanoe"
        service: "tippecanoe"
        cleanup: true